#!/bin/bash
#
# make an image with{,out} OpenSCAD

set -euo pipefail

export DOCKER_KIT=1

flavours="base openscad"

function getImageTag {
  local -r image_flavour="${1:-${DOCKER_TAG:-latest}}"

  echo "${DOCKER_REPO:-dmote}:${image_flavour}"
}

case "${0##*/}" in
  build)
    docker build -t "$(getImageTag)" -f "${DOCKERFILE_PATH:-./Dockerfile}"
    docker build --build-args WITH=openscad -t "$(getImageTag openscad)" -f "${DOCKERFILE_PATH:-./Dockerfile}"
    ;;
  push)
    docker push "$(getImageTag)"
    docker push "$(getImageTag openscad)"
    ;;
  *)
    echo "Unknown caller: $0" >&2
    exit 1
    ;;
esac
    
