#!/bin/bash
#
# make an image with{,out} OpenSCAD

set -euo pipefail

export DOCKER_KIT=1

flavours="base openscad"

function getImageTag {
  local -r image_flavour="${1:?arg1 is flavour}"

  echo "${DOCKER_REPO:-dmote}:${image_flavour}-${DOCKER_TAG:-latest}"
}

basename="${0##*/}"
case 
  build)
    for image_flavour in ${flavours}; do
      docker build --build-args WITH="${image_flavour}" -t "$(getImageTag ${image_flavour})" -f "${DOCKERFILE_PATH:-./Dockerfile}"
    done
    ;;
  push)
    for image_flavour in ${flavours}; do
      docker push "$(getImageTag ${image_flavour})"
    done
    ;;
  *)
    echo "Unknown caller: $0" >&2
    exit 1
    ;;
esac
    
